<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>tedium</ToolCommandName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="CLI\AnsiCodes.fs" />
    <Compile Include="CLI\ScreenBuffer.fs" />
    <Compile Include="CLI\InputThread.fs" />
    <Compile Include="CLI\Keymap.fs" />
    <Compile Include="CLI\CommandBuffer.fs" />
    <Compile Include="CLI\TextBuffer.fs" />
    <Compile Include="GitHub\Issues.fs" />
    <Compile Include="GitHub\GitHub.fs" />
    <Compile Include="TodoList\Tag.fs" />
    <Compile Include="TodoList\TodoItem.fs" />
    <Compile Include="TodoList\TodoItemParser.fs" />
    <Compile Include="TodoList\TodoItemWriter.fs" />
    <Compile Include="TodoList\TodoListRoot.fs" />
    <Compile Include="TodoList\SearchQuery.fs" />
    <Compile Include="TodoList\Operations.fs" />
    <Compile Include="State\Modes\NormalMode.fs" />
    <Compile Include="State\Modes\SearchMode.fs" />
    <Compile Include="State\Modes\Mode.fs" />
    <Compile Include="State\State.fs" />
    <Compile Include="State\NormalModeCommands.fs" />
    <Compile Include="State\SearchModeCommands.fs" />
    <Compile Include="State\StateCommands.fs" />
    <Compile Include="UI\View.fs" />
    <Compile Include="Tedium.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>